name: Compile with SourceMod

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '53 05 01 */3 *' # Artifacts expire every 3 months

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ '1.10', '1.11' ]

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch_name

      - name: Set environment variables
        run: |
          git fetch --unshallow
          echo "COMMIT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git describe --always --long --dirty)" >> $GITHUB_ENV

          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "PLUGINS_PATH=$SOURCEMOD_PATH/plugins" >> $GITHUB_ENV
          echo "GAMEDATA_PATH=$SOURCEMOD_PATH/gamedata" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
          echo "TRANSLATIONS_PATH=$SOURCEMOD_PATH/translations" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Set Version
        run: |
          sed -i "s/<VERSION>/${{ steps.get_branch_name.outputs.branch }}.${{ env.COMMIT }}.${{ env.SHORT_SHA }}.SM${{ matrix.SM_VERSION }}/g" $SCRIPTING_PATH/include/fuckTimer_stocks.inc

      - name: Compile fuckTimer plugins
        run: |
          mkdir -p $PLUGINS_PATH/fucktimer
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTING_PATH/include -o $PLUGINS_PATH/fucktimer/$file $file
          done
        working-directory: ${{ env.SCRIPTING_PATH }}/fuckTimer

      - name: Download 3rd party plugins
        run: |
          wget https://github.com/rumourA/End-Touch-Fix/raw/master/scripting/EndTouchFix.sp -P $SCRIPTING_PATH
          wget https://github.com/rumourA/End-Touch-Fix/raw/master/gamedata/endtouch.games.txt -P $GAMEDATA_PATH
          wget https://github.com/Bara/fuckZones/raw/master/addons/sourcemod/scripting/fuckZones.sp -P $SCRIPTING_PATH
          wget https://github.com/Bara/fuckZones/raw/master/addons/sourcemod/translations/fuckZones.phrases.txt -P $TRANSLATIONS_PATH

      - name: Compile 3rd party plugins
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTING_PATH/include -o $PLUGINS_PATH/$file $file
          done
        working-directory: ${{ env.SCRIPTING_PATH }}

      - name: Prepare package directory
        run: |
          rm -R addons/sourcemod/scripting
          mkdir package
          mv ./{addons,cfg,LICENSE,README.md} package

      - name: Create archive
        uses: actions/upload-artifact@v2
        with:
          name: fuckTimer.${{ steps.get_branch_name.outputs.branch }}.${{ env.COMMIT }}.${{ env.SHORT_SHA }}.SM${{ matrix.SM_VERSION }}
          path: package
